#!usr/bin/env php
<?php
/**
 * Mubu - A simple framework for PHP Developers
 *
 * @package  Mubu
 * @author   İzni Burak Demirtaş <izniburak@gmail.com>
 * @web      <http://burakdemirtas.org>
 */

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Mubu\Console\Command;

$console = new Command( new Application("mubu - simple PHP Framework") );
$console->run();
