#!usr/bin/env php
<?php
/**
* nur - a simple framework for PHP Developers
*
* @author   izni burak demirtaş (@izniburak) <izniburak@gmail.com>
* @web      <http://burakdemirtas.org>
* @url      <https://github.com/izniburak/nur>
* @license  The MIT License (MIT) - <http://opensource.org/licenses/MIT>
*/

require __DIR__.'/vendor/autoload.php';

use Nur\Kernel\Kernel;
use Nur\Console\Command;
use Symfony\Component\Console\Application;
use Symfony\Component\Yaml\Yaml;
use Symfony\Component\Yaml\Exception\ParseException;

$app = new Kernel();
$config = $app->config();

define('NUR_VERSION', Kernel::VERSION);
define('ROOT', $app->root());
define('DOC_ROOT', $app->docRoot());
define('BASE_FOLDER', $app->baseFolder());

$console = new Command( new Application("       _ __  _   _ _ __
      | '_ \| | | | '__|
      | | | | |_| | |
      |_| |_|\__,_|_|
  nur - Simple PHP Framework") );
$console->run();
