#!usr/bin/env php
<?php
/**
 * nur - a simple framework for PHP Developers
 *
 * @author   izni burak demirtaş (@izniburak) <izniburak@gmail.com>
 * @web      <http://burakdemirtas.org>
 * @url      <https://github.com/izniburak/nur>
 * @license  The MIT License (MIT) - <http://opensource.org/licenses/MIT>
 */

require __DIR__.'/vendor/autoload.php';

use Nur\Kernel\Application;
use Nur\Console\Command;
use Symfony\Component\Console\Application as ConsoleApplication;

$app = new Application;

define('NUR_VERSION', $app->version());
define('ROOT', $app->root());
define('DOC_ROOT', $app->docRoot());
define('BASE_FOLDER', $app->baseFolder());

$console = new Command(new ConsoleApplication("      _ __  _   _ _ __
     | '_ \| | | | '__|
     | | | | |_| | |
     |_| |_|\__,_|_| v" . NUR_VERSION . "
  nur - Simple PHP Framework"), $app);
$console->run();
